#!/bin/bash

RUN_EXE="$(find "${WINEPREFIX}" -name "FusionLauncher.exe.ini" | head -1 | xargs -I '{}' echo {} | head -c-5)"
echo "updated RUN_EXE=${RUN_EXE}"

cat > "$WINEPREFIX/drive_c/Program Files/Autodesk/webdeploy/meta/update.bat" << "E"
@echo off
set "StreamerDir=c:\Program Files\Autodesk\webdeploy\meta\streamer"
setlocal
FOR /F %%i IN ('dir /A:D /B /oN "%StreamerDir%"') DO (
  SET a=%%i
)
endlocal & set StreamerVer=%a%
"%StreamerDir%\%StreamerVer%\streamer.exe" --globalinstall --process update --quiet
E
